version: '3'
volumes:
  arriba:

services:
  base:
    image: ericmaino/elfie-arriba:latest
    build: 
      context: ./src
      dockerfile: Dockerfile
  crawler:
    image: ericmaino/elfie-arriba:crawler-latest
    build: 
      context: .docker/Crawler
      dockerfile: Dockerfile
    depends_on:
      - base
    volumes:
      - arriba:/Arriba/DiskCache
    environment:
      ARRIBA__APPLICATIONVERSION: "DevMachine"
      ARRIBA__SERVICENAME: "Crawler"
      ARRIBA__AZPAT: ${AZPAT}
  server:
    image: ericmaino/elfie-arriba:server-latest
    build: 
      context: .docker/Server
      dockerfile: Dockerfile
    depends_on:
      - base
    volumes:
      - arriba:/Arriba/DiskCache
    environment:
      ARRIBASERVER__APPLICATIONVERSION: "DevMachine"
      ARRIBASERVER__SERVICENAME: "Server"
      ARRIBASERVER__OAUTHCONFIG__APPSECRET: ${APPSECRET}
  web:
    image: ericmaino/elfie-arriba:web-latest
    build: 
      context: .docker/WebUI
      dockerfile: Dockerfile
    depends_on:
      - base
    ports:
      - 8080:80
